# Generated by Django 2.1.5 on 2020-03-30 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nowandthen', '0002_auto_20200330_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='nowandthen.Picture'),
        ),
    ]
